package es.alumnosupm.hugoalvarezajenjo.view;

import es.alumnosupm.hugoalvarezajenjo.logic.FileMenuActions;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * The `EditorViewListerner` class is responsible for handling action events generated by the user interface elements in the Notepad application. It implements the ActionListener interface to respond to user interactions.
 *
 * @author Hugo Alvarez Ajenjo
 * @version 0.0
 */
public class EditorViewListerner implements ActionListener {

    final EditorView editorView;
    final FileMenuActions fileMenuActions;

    /**
     * Constructor for the EditorViewListener class that initializes an instance of the EditorView and Logic classes.
     * It establishes a link between the GUI and the application logic.
     */
    public EditorViewListerner() {
        editorView = new EditorView(this);
        fileMenuActions = new FileMenuActions(editorView);
    }

    /**
     * Handles action events generated by user interface elements such as menu items.
     * The method performs different actions based on the action command provided by the source of the event.
     *
     * @param e The ActionEvent generated by the user's interaction.
     */
    @Override
    public void actionPerformed(final ActionEvent e) {
        final String command = e.getActionCommand();

        switch (command) {
            case "New" -> fileMenuActions.newFile();
            case "Open" -> fileMenuActions.openFile();
            case "Save" -> fileMenuActions.saveFile();
            case "Save As" -> fileMenuActions.saveAsFile();
            case "Exit" -> fileMenuActions.exitProgram();
        }


    }
}
